version: '3'

services:

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=0.0.0.0
      - PASSWORD=SET_YOUR_PASS
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  squid-easy:
   image: ckazi/squid-easy
   container_name: squid-easy
   ports:
     - "51823:8080"
   environment:
     - GIN_MODE=release
     - SQUID_PASSWORD=SET_YOUR_PASS
   volumes:
     - ./config:/app/config:rw
   restart: always

  squid:
    image: ckazi/squid
    container_name: squid
    ports:
      - "51822:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - ./config/squid_passwd:/etc/squid/squid_passwd:ro
    restart: always