version: '3'

services:

  squid-easy:
   image: ckazi/squid-easy
   container_name: squid-easy
   ports:
     - "51823:8080"
   environment:
     - GIN_MODE=release
     - SQUID_PASSWORD=SET_YOUR_PASS
   volumes:
     - ./config/squid_passwd:/app/config/squid_passwd:rw
   restart: always

  squid:
    image: ckazi/squid
    container_name: squid
    ports:
      - "51822:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - ./config/squid_passwd:/etc/squid/squid_passwd:ro
    restart: always
